name: "Lint Commits"

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  conventional-commits:
    name: Check Commits Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history so all commits in the PR can be checked

      - name: Lint Commits
        uses: webiny/action-conventional-commits@v1.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
